channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.19.0
  - numpy==1.26.3
  - pandas==2.2.0
  - psutil==5.9.7
  - scikit-learn==1.5.2
  - scipy==1.12.0
  - xgboost==2.1.3
name: mlflow-env
