name: CI/CD Pipeline for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Étape 1 : Tests unitaires
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r tests_unitaires/requirements.txt

      - name: Run unit tests
        run: |
          pytest tests_unitaires/

  # Étape 2 : Build des microservices Docker
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t myorg/api_model ./src/api_model
          docker build -t myorg/gateway ./src/Gateway
          docker build -t myorg/ingest ./src/ingest
          docker build -t myorg/preprocess ./src/preprocess
          docker build -t myorg/train ./src/train
          docker build -t myorg/streamlit_app ./src/streamlit_app
