FROM python:3.9-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./src/preprocess/ /app/src/preprocess/
COPY ./data/raw/weatherAUS.csv /app/data/raw/weatherAUS.csv
COPY ./dvc.yaml /app/dvc.yaml

RUN pip install --no-cache-dir -r /app/src/preprocess/requirements.txt dvc
RUN dvc init --no-scm


CMD ["python", "/app/src/preprocess/preprocess.py"]