stages:
  ingestion:
    cmd: python src/ingest/script_meteo.py
    outs:
      - data/raw/weatherAUS.csv
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - config/config.yaml
      - data/raw/weatherAUS.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/.gitignore

  train:
    cmd: python src/xgboost_model.py
    deps:
      - src/xgboost_model.py
      - config/config.yaml
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - model/xgboost_model.json
      - metrics/metrics.json
