name: CI for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     service: [ingest, preprocess, train] # Liste des services

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Python 3.12 pour l’ingest
      - name: Setup Python 3.12 for ingest
        id: python312
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies (ingest)
        run: ${{ steps.python312.outputs.python-path }}/bin/pip install -r ./src/ingest/requirements.txt
      
      - name: Build Docker image (ingest)
        run: docker build -t ingest-test:local ./src/ingest/

      # Configurer Python 3.9 pour le preprocess
      - name: Setup Python 3.9 for preprocess
        id: python39
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies (preprocess)
        run: ${{ steps.python39.outputs.python-path }}/bin/pip install -r ./src/preprocess/requirements.txt
      
      - name: Run unit tests (preprocess)
        run: ${{ steps.python39.outputs.python-path }}/bin/pytest ./tests_unitaires/test_preprocess.py --maxfail=3 --disable-warnings
      
      - name: Build Docker image (preprocess)
        run: docker build -t preprocess-test:local ./src/preprocess/


        

# name: CI for Microservices

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   list-services:
#     runs-on: ubuntu-latest
#     outputs:
#       services: ${{ steps.list.outputs.services }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: List Services
#         id: list
#         run: |
#           echo "$(ls -d src/*/ | xargs -n 1 basename | jq -R -s -c 'split(\"\\n\")[:-1]')" > services.json
#           echo "::set-output name=services::$(cat services.json)"

#   test-and-build:
#     runs-on: ubuntu-latest
#     needs: list-services
#     strategy:
#       matrix:
#         service: ${{ fromJson(needs.list-services.outputs.services) }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install dependencies
#         run: pip install -r ./src/${{ matrix.service }}/requirements.txt

#       - name: Run unit tests
#         run: pytest ./src/${{ matrix.service }}/tests_unitaires/ --maxfail=3 --disable-warnings

#       - name: Build Docker images
#         run: docker build -t ${{ matrix.service }}:local ./src/${{ matrix.service }}

    
