name: CI for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ingest, preprocess, train] # Liste des services

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer DVC et récupérer les données depuis DagsHub
      - name: Install DVC & Pull Data
        run: |
          pip install dvc
          dvc remote add origin https://dagshub.com/bmle-aug24/Meteo_group.dvc
          dvc remote modify origin auth basic
          dvc remote modify origin user bmle-aug24
          dvc remote modify origin password 80f0fd7d1ab6a2b1e95664936d78045d71c78e17
          dvc pull

      # Étape 3 : Installer les dépendances Python
      - name: Install dependencies
        run: pip install -r ./src/${{ matrix.service }}/requirements.txt

      # Étape 4 : Exécuter les tests unitaires
      - name: Run unit tests
        run: pytest src/${{ matrix.service }}/tests/

      # Étape 5 : Construire les images Docker
      - name: Build Docker images
        run: docker build -t ${{ matrix.service }}:local ./src/${{ matrix.service }}


          
