name: CI for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     service: [ingest, preprocess, train] # Liste des services

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.12 for ingest
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies (ingest)
        run: pip install -r ./src/ingest/requirements.txt
      
      - name: Build Docker image (ingest)
        run: docker build -t ingest-test:local ./src/ingest/

  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python 3.9 for preprocess
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies (preprocess)
        run: pip install -r ./src/preprocess/requirements.txt
      
      # - name: Run unit tests (preprocess)
      #   run: pytest ./tests_unitaires/test_preprocess.py --maxfail=3 --disable-warnings
      
      - name: Build Docker image (preprocess)
        run: docker build -t preprocess-test:local ./src/preprocess/


  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python 3.11.8 for train
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'

      - name: Install dependencies (train)
        run: pip install -r ./src/train/requirements.txt

      # - name: Run unit tests (train)
      #   run: pytest ./tests_unitaires/test_train.py --maxfail=3 --disable-warnings

      - name: Run train script
        run: python ./src/train/train.py

      - name: Build Docker image (train)
        run: docker build -t train-test:local ./src/train/



        

# name: CI for Microservices

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   list-services:
#     runs-on: ubuntu-latest
#     outputs:
#       services: ${{ steps.list.outputs.services }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: List Services
#         id: list
#         run: |
#           echo "$(ls -d src/*/ | xargs -n 1 basename | jq -R -s -c 'split(\"\\n\")[:-1]')" > services.json
#           echo "::set-output name=services::$(cat services.json)"

#   test-and-build:
#     runs-on: ubuntu-latest
#     needs: list-services
#     strategy:
#       matrix:
#         service: ${{ fromJson(needs.list-services.outputs.services) }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install dependencies
#         run: pip install -r ./src/${{ matrix.service }}/requirements.txt

#       - name: Run unit tests
#         run: pytest ./src/${{ matrix.service }}/tests_unitaires/ --maxfail=3 --disable-warnings

#       - name: Build Docker images
#         run: docker build -t ${{ matrix.service }}:local ./src/${{ matrix.service }}

    
