name: CI for Microservices (Local Build)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ingest, preprocess, train] # Liste des services à tester

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r ./src/${{ matrix.service }}/requirements.txt

      - name: Run unit tests
        run: |
          pytest tests_unitaires/test_${{ matrix.service }}.py

  build:
    needs: test # Ce job ne s'exécute que si les tests réussissent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ingest, preprocess, train] # Liste des services à construire

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images # va lancer successivement la construction des images pour chaque service ingest preprocess et train
        run: |
          docker build -t ${ matrix.service }:local ./src/${{ matrix.service }}
          

